version: '3.8'

services:

  nginx:
    image: nginx:1.19.7-alpine
    ports:
      - "8080:80"
    links:
      - php-fpm
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default

      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./logs/nginx-error.log:/var/log/nginx/error.log

  php-fpm:
    image: php:8.0.2-fpm-buster
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app
